version: "3"

services:
    db:
        container_name: postgresblog
        image: postgres
        restart: always
        environment: 
            - POSTGRES_PASSWORD=postgres
        volumes: 
            - blog_data:/var/lib/postgresql/data
    dj:
        container_name: djangoblog
        build: .
        image: djblog:blog
        working_dir: /BlogApp
        command: uwsgi --ini uwsgi.ini
        restart: always
        depends_on:
            - db
            - elasticsearch
        environment: 
            - DJANGO_SETTINGS=dev
            # - ENABLE_HAYSTACK_REALTIME_SIGNAL_PROCESSOR=no
    ng:
        container_name: nginxblog
        build: 
            context: .
            dockerfile: ./Dockerfile_ng
        restart: always
        ports: 
            - "80:80"
        depends_on: 
            - dj
    elasticsearch:
        build:
            context: .
            dockerfile: Dockerfile_search
        image: blog_app_elasticsearch
        container_name: blog_app_elasticsearch
        # command: ['sysctl', '-w', 'vm.max_map_count=262144']
        restart: always
        volumes:
            - esdata:/usr/share/elasticsearch/data
        # ports:
            # - "9200:9200"
        environment:
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nproc: 65536
            nofile:
                soft: 65536
                hard: 65536
volumes: 
    blog_data:
    esdata:
        